### ISSUE TITLE
What does your cluster look like?

### ISSUE THREAD

**Issue by CrocoDillon** [rhsimplex/image-match#29]
First of al thanks for this project! :shipit: 

> includes a database backend that easily scales to billions of images and supports sustained high rates of image insertion: up to 10,000 images/s on our cluster!

I was wondering what that cluster would look like. How many and what types of nodes for image-match and for Elasticsearch, as well as CPU and memory for each. I'm thinking of using Google's container engine (Kubernetes) for deployment and need to estimate cost.

**Comment by rhsimplex** [comment]
Hi @CrocoDillon, glad you're finding the project useful.

We originally wrote image-match to support a web crawl, so the architecture was something like a few beefy elasticsearch nodes (something like 3-5 32-core machines) supported by as many crawlers as we wanted -- typically AWS spot instances of 4-16 core machines.  The crawl was io-bound, but the actual image processing and database storage is cpu-bound.  With signature compression #2, we could reduce the hardware requirement. 

If you're going to go for 10k images/s, you really need to use elasticsearch's bulk insert functionality instead of inserting one image at time.  It's not in the current stable version of image match, but you can get an idea of how to do it from an [old commit](https://github.com/ascribe/image-match/blob/f6e8d1bccf85e23829448ab1289d42d58dcd8ef5/image_match/signature_database.py#L110).

If you end up rewriting the bulk insert into the current codebase, please do make a pull request!
